---
dist: focal
language: generic
matrix:
  fast_finish: true
  include:
    - name: ARM Equinix Metal Test (Arm64 v8 Build.)
      os: linux
      dist: focal
      arch: arm64 # (Armv8 Equinix Metal)
      language: python
      python: 3.7
      install: skip
      before_script: skip
      script: python3 bfs.py
      env:
        - LIB_PATH="/usr/bin/shared/x86_64/v1"
